[package]
name = "gurobi_demo"
version = "0.1.0"
authors = ["Qingru Zhang <qzhang1@macalester.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

gurobi = "0.3.4"
